name: Create Release Unpackaged
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string

jobs:
  feature-test:
    name: "Create Release in GitHub"
    runs-on: ubuntu-latest
    steps:
      - uses: MuseDeploy/release-production-unmanaged@main
        with:
          version: ${{ inputs.version }}
          cumulusci-version: ${{ inputs.cumulusci-version }}
          sfdx-version: ${{ inputs.sfdx-version }}
