name: Create Release Unpackaged
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string

jobs:
  create-release:
    name: "Create Release in GitHub"
    runs-on: ubuntu-latest
    steps:
      - uses: MuseDeploy/release-production-unmanaged@main
        with:
          version: ${{ inputs.version }}
          cumulusci-version: ${{ inputs.cumulusci-version }}
          sfdx-version: ${{ inputs.sfdx-version }}
      - uses: musedeploy/standard-workflows/.github/workflows/metadeploy-pub
  publish-release:
    name: "Publish Release to MuseDeploy"
    needs:
      - create-release
    uses: musedeploy/standard-workflows/.github/workflows/musedeploy-publish.yml@main
    secrets:
      cumulusci-service-metadeploy: "${{ secrets.CUMULUSCI_SERVICE_METADEPLOY }}"
    with:
      version: ${{ inputs.version }}
      cumulusci-version: ${{ inputs.cumulusci-version }}
      sfdx-version: ${{ inputs.sfdx-version }}
    
        