on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      tag:
        required: true
        type: string
      plan:
        required: false
        type: string
      dry-run:
        required: false
        default: false
        type: boolean
      publish:
        required: false
        default: true
        type: boolean
    secrets:
      cumulusci-service-metadeploy:
        required: true

jobs:
  metadeploy-publish:
    name: "Publish to MuseDeploy"
    runs-on: ubuntu-latest
    steps:
      - uses: musedeploy/metadeploy-publish@main
        with:
          cumulusci-service-metadeploy: "${{ secrets.cumulusci-service-metadeploy }}"
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
          tag: "${{ inputs.tag }}"
          plan: "${{ inputs.plan }}"
          dry-run: "${{ inputs.dry-run }}"
          publish: "${{ inputs.publish }}"
